# This file was generated by GoReleaser. DO NOT EDIT.
cask "proximo" do
  version "0.11.0"

  on_macos do
    on_arm do
      sha256 "7ee89c45fe6b49daa72917aaa35b6b94c75d4fd5adb96d632f90694484ef45d5"
      url "https://github.com/filippolmt/proximo/releases/download/v#{version}/proximo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "27cf41623bc5c300f717ed725a22ca25bb780a421ac4988310ca48a9e282a189"
      url "https://github.com/filippolmt/proximo/releases/download/v#{version}/proximo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e1d59e7539ecb60fa72cbdd49bc5cfa94575df7fc6ce839f230d9908fa4eb16a"
      url "https://github.com/filippolmt/proximo/releases/download/v#{version}/proximo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ba469742d27ba5282e9ddd4fbe42ad01b536028bcb80727d43cfb9ae2d159a22"
      url "https://github.com/filippolmt/proximo/releases/download/v#{version}/proximo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "proximo"
  desc "Local development reverse proxy with automatic DNS and trusted HTTPS"
  homepage "https://github.com/filippolmt/proximo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "proximo"

  postflight do
    # The binary is unsigned; strip the quarantine attribute so macOS
    # Gatekeeper does not refuse to run it with an "is damaged" alert.
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/proximo"]
    end
    # `proximo update` is a soft no-op that exits 0 when Docker is
    # unreachable or no stack is running, so it is safe in a hook. It is
    # not allowed to fail the upgrade either way: a stack that cannot
    # converge now converges on the next `proximo up`.
    system_command "#{staged_path}/proximo", args: ["update"],
                   must_succeed: false, print_stdout: true
  end

  # No zap stanza required

  caveats <<~EOS
    The running stack is converged to this CLI version on install. If Docker
    was not running, it converges on the next `proximo up` — or run
    `proximo update` yourself; it never needs sudo.
  EOS
end
