# This file was generated by GoReleaser. DO NOT EDIT.
cask "proximo" do
  version "0.12.0"

  on_macos do
    on_arm do
      sha256 "fe69a619fc95af0e22ba1530fe9eccfe2ebb52c93369be129fc902eabd406a36"
      url "https://github.com/filippolmt/proximo/releases/download/v#{version}/proximo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "51a604df061c063457b4a9d454d5e4f9c06619c075114104fe601dc2e66256dd"
      url "https://github.com/filippolmt/proximo/releases/download/v#{version}/proximo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "975a0c297dd42dc5e78858ccfc89636cc75155132dd6b219fe68b3e244871aea"
      url "https://github.com/filippolmt/proximo/releases/download/v#{version}/proximo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "96078eac82e7698b3077014d6705efd6baabb68048eb0a160e3ed5289f285e23"
      url "https://github.com/filippolmt/proximo/releases/download/v#{version}/proximo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "proximo"
  desc "Local development reverse proxy with automatic DNS and trusted HTTPS"
  homepage "https://github.com/filippolmt/proximo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "proximo"

  postflight do
    # The binary is unsigned; strip the quarantine attribute so macOS
    # Gatekeeper does not refuse to run it with an "is damaged" alert.
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/proximo"]
    end
    # `proximo update` is a soft no-op that exits 0 when Docker is
    # unreachable or no stack is running, so it is safe in a hook. It is
    # not allowed to fail the upgrade either way: a stack that cannot
    # converge now converges on the next `proximo up`.
    system_command "#{staged_path}/proximo", args: ["update"],
                   must_succeed: false, print_stdout: true
  end

  # No zap stanza required

  caveats <<~EOS
    The running stack is converged to this CLI version on install. If Docker
    was not running, it converges on the next `proximo up` — or run
    `proximo update` yourself; it never needs sudo.
  EOS
end
