# This file was generated by GoReleaser. DO NOT EDIT.
cask "proximo" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "138d26c583faf87fc595cff7ca59c78f6a2c0c3face409a947ca36be78368d88"
      url "https://github.com/filippolmt/proximo/releases/download/v#{version}/proximo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6aa77adb802fa0bd4868a9bb407c6c45e7dd878367d257162ca978413d56b9d2"
      url "https://github.com/filippolmt/proximo/releases/download/v#{version}/proximo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2888ad4cded76debde28fa92f794985499635237effe659ef4acc3dcd7f074b3"
      url "https://github.com/filippolmt/proximo/releases/download/v#{version}/proximo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "291d5a349a78fdd4c9d94f631bc8f0b6c85db7953becacb87746fa370f5a5522"
      url "https://github.com/filippolmt/proximo/releases/download/v#{version}/proximo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "proximo"
  desc "Local development reverse proxy with automatic DNS and trusted HTTPS"
  homepage "https://github.com/filippolmt/proximo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "proximo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/proximo"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To converge the running stack with this CLI version, run:
      proximo update
    Safe to run any time; if Docker is not running it applies on the next
    `proximo up`.
  EOS
end
