# This file was generated by GoReleaser. DO NOT EDIT.
cask "toolbox" do
  version "0.88.2"

  on_macos do
    on_arm do
      sha256 "514a6bfa3e9baf9a4950e186ee9e8c5278855419b48c1696fa7cdd208e4bcdb7"
      url "https://github.com/filippolmt/toolbox/releases/download/v#{version}/toolbox_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e8ff4fb30a8bccdfd54e85f418384ca6a9b70c750328778d3166a64021b660a1"
      url "https://github.com/filippolmt/toolbox/releases/download/v#{version}/toolbox_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "32a75e28717af5115234915f9746eaa43d5f10892e58b6d9f0f1966637730813"
      url "https://github.com/filippolmt/toolbox/releases/download/v#{version}/toolbox_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5569eb063672acb84cadd12d8c1ae2473d2332acfcf0556835ff907cd89b070a"
      url "https://github.com/filippolmt/toolbox/releases/download/v#{version}/toolbox_#{version}_linux_amd64.tar.gz"
    end
  end

  name "toolbox"
  desc "CLI for the containerized dev toolbox"
  homepage "https://github.com/filippolmt/toolbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toolbox"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/toolbox"]
    end
  end

  generate_completions_from_executable "toolbox", "completion",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
