# This file was generated by GoReleaser. DO NOT EDIT.
cask "toolbox" do
  preflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/toolbox"]
    end
  end

  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "2a741e29b9a90af9af802e5e57d3432a384996834048fe22e7d0786a954af519"
      url "https://github.com/filippolmt/toolbox/releases/download/v#{version}/toolbox_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d4dbaf1e6978d06a0b93abdad6257ab88a52cfeb6c3841f4866249506837e533"
      url "https://github.com/filippolmt/toolbox/releases/download/v#{version}/toolbox_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8c1eb009b52db9cb90fefccf07a723b77c6b7f9bbdf8ebe6000daa289ef988bc"
      url "https://github.com/filippolmt/toolbox/releases/download/v#{version}/toolbox_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "05990560e2d27a66e1bb495db52c694979a5060e33cec9120d68d50431d22336"
      url "https://github.com/filippolmt/toolbox/releases/download/v#{version}/toolbox_#{version}_linux_amd64.tar.gz"
    end
  end

  name "toolbox"
  desc "CLI for the containerized dev toolbox"
  homepage "https://github.com/filippolmt/toolbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toolbox"

  generate_completions_from_executable "toolbox", "completion",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
