# This file was generated by GoReleaser. DO NOT EDIT.
cask "toolbox" do
  version "0.43.0"

  on_macos do
    on_intel do
      sha256 "f399b046c21458e6e3fa78e181b8fadd4dee0d4946c5853705d7a45aa5084d4d"
      url "https://github.com/filippolmt/toolbox/releases/download/v#{version}/toolbox_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7672566f20c46055811c95fa3508956833ad92d887639429923a9953cd39f304"
      url "https://github.com/filippolmt/toolbox/releases/download/v#{version}/toolbox_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "50a0ee460f9094f8246c987af3b24c7b02a6ce28aa66e4436105baf70952742b"
      url "https://github.com/filippolmt/toolbox/releases/download/v#{version}/toolbox_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "695098162719b893513a55812780809890ddeb52533013b2cfcc640c867b624e"
      url "https://github.com/filippolmt/toolbox/releases/download/v#{version}/toolbox_#{version}_linux_arm64.tar.gz"
    end
  end

  name "toolbox"
  desc "CLI for the containerized dev toolbox"
  homepage "https://github.com/filippolmt/toolbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toolbox"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/toolbox"]
    end
  end

  # No zap stanza required

end
