# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toolbox < Formula
  desc "CLI for the containerized dev toolbox"
  homepage "https://github.com/filippolmt/toolbox"
  version "0.13.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/filippolmt/toolbox/releases/download/v0.13.0/toolbox_0.13.0_darwin_amd64.tar.gz"
      sha256 "0454535db7de9b5b56f53965dbac67f528844dc1e83188f131ff305fb789b56c"

      define_method(:install) do
        bin.install "toolbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/filippolmt/toolbox/releases/download/v0.13.0/toolbox_0.13.0_darwin_arm64.tar.gz"
      sha256 "9d6f69e7b034c00ca2aa872d5fd2968c69ee167608c84bae3078094ac98bb2e8"

      define_method(:install) do
        bin.install "toolbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/filippolmt/toolbox/releases/download/v0.13.0/toolbox_0.13.0_linux_amd64.tar.gz"
      sha256 "d04de1bf04d6d8969a057c0584fb6f19809dcad466c354e1f159123407bc34a5"
      define_method(:install) do
        bin.install "toolbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/filippolmt/toolbox/releases/download/v0.13.0/toolbox_0.13.0_linux_arm64.tar.gz"
      sha256 "d0a9d70bbfb5d9a4b85406496c291461dabf611cbebe438d1a7d66a68ef8d069"
      define_method(:install) do
        bin.install "toolbox"
      end
    end
  end

  test do
    system "#{bin}/toolbox", "--version"
  end
end
