# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toolbox < Formula
  desc "CLI for the containerized dev toolbox"
  homepage "https://github.com/filippolmt/toolbox"
  version "0.34.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/filippolmt/toolbox/releases/download/v0.34.0/toolbox_0.34.0_darwin_amd64.tar.gz"
      sha256 "7533895acbe47264cac6aa1974d4290b6fae402c0045c92a550760bbfb73c89a"

      define_method(:install) do
        bin.install "toolbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/filippolmt/toolbox/releases/download/v0.34.0/toolbox_0.34.0_darwin_arm64.tar.gz"
      sha256 "2d94f8f6264bc47e2ad27de174a866f3c90d311ce8706d5411a8121f31c74909"

      define_method(:install) do
        bin.install "toolbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/filippolmt/toolbox/releases/download/v0.34.0/toolbox_0.34.0_linux_amd64.tar.gz"
      sha256 "4abf1f05d3306ee8aa2682baacdf930a1deb5be1c80c41ced64630cf1b495ca6"
      define_method(:install) do
        bin.install "toolbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/filippolmt/toolbox/releases/download/v0.34.0/toolbox_0.34.0_linux_arm64.tar.gz"
      sha256 "fd187acbaaffb5b25d7e81a65ab05580f0fda159f2ffdb69b8dbfad4e60617a4"
      define_method(:install) do
        bin.install "toolbox"
      end
    end
  end

  test do
    system "#{bin}/toolbox", "--version"
  end
end
